#
# Copyright (c) 2013-2016, The SeedStack authors <http://seedstack.org>
#
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.
#

security:
  users:
    ThePoltergeist:
      password: bouh
      roles: [SEED.MU.GHOST, SEED.PY.GHOST, SEED.JEDI]
  roles:
    jedi: SEED.JEDI
    ghost: SEED.{scope}.GHOST
  permissions:
    jedi: ['lightSaber:*', 'academy:*']
    ghost: 'site:haunt'
  web:
    urls:
      -
        pattern: /**
        filters: authcBasic
